version: "3"

services:
  db:
    env_file: ./app/.env
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data
  job:
    depends_on:
      - db
    image: ehddnr/investment-data-pipeline:1.0.0
    container_name: data-pipeline-job
volumes:
  db_home:
    external: false