version: "3.3"

services:
  db:
    env_file: ./app/.env
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_home:/var/lib/postgresql/data
  job:
    depends_on:
      - db
    ports:
      - "4200:4200"
    environment:
      - PREFECT_ORION_API_HOST=127.0.0.1
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-credentials
    image: ehddnr/investment-data-pipeline:3.0.0
    container_name: data-pipeline-job
    secrets:
      - gcp-credentials

secrets:
  gcp-credentials:
    file: ./bright-eon-368611-4dc130fe8191.json

volumes:
  db_home:
    external: false